name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup environment
        run: |
          cp .env.example .env
          echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" >> .env

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test --runInBand

      - name: Build
        run: pnpm build
